name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Check required files
        id: check_required_files
        uses: andstor/file-existence-action@v1
        with:
          files: "github-desktop-screenshot.png"

      - name: Check branch name
        run: |
          if [[ ${{ steps.extract_branch.outputs.branch }} != "desktop" ]]; then
            echo "The branch must be named 'desktop'"
            exit 1
          fi
        shell: bash
